spring:
  thymeleaf:
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
  jackson:
    time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.address}:3306/aurora-chat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT%2B8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath*:mapper/*
  type-aliases-package: com.chat.aurorachat.dataobject

